# Generated by Django 2.2.6 on 2019-10-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_auto_20191019_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
