# Generated by Django 2.2.6 on 2020-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_auto_20191019_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='typework',
            name='slug',
            field=models.SlugField(default='Null'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='technology',
            field=models.TextField(default='Null'),
        ),
    ]
